#include "nw_i0_tool"
/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.2

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this on action taken in the conversation editor
void main()
{

object oPC = GetPCSpeaker();

if (GetLocalInt(oPC, "Davis_XP")== 0)
   {
   RewardPartyXP(100, oPC, FALSE);

   SetLocalInt(oPC, "Davis_XP", 1);

   }
}

