/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.2

For download info, please visit:
http://www.angelfire.com/space/lilacsoul    */

//Put this on action taken in the conversation editor
void main()
{

object oPC = GetPCSpeaker();

AdjustAlignment(oPC, ALIGNMENT_EVIL, 1);

}

