/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.2

For download info, please visit:
http://www.angelfire.com/space/lilacsoul    */

//Put this OnOpen
void main()
{

object oPC = GetLastOpenedBy();

if (!GetIsPC(oPC)) return;

object oTarget;
oTarget = GetNearestObjectByTag("Slave", OBJECT_SELF,1);

AssignCommand(oTarget, ClearAllActions());

AssignCommand(oTarget, ActionStartConversation(oPC, "slavetalk"));

}

