/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Goes on creature's OnHeartbeat. Fires when not fighting or talking.
void main()
{

    AssignCommand(OBJECT_SELF, ActionSit(GetObjectByTag("rexchair")));
}

