#include "nw_i0_generic"
/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

//Put this OnEnter
void main()
{

object oPC = GetEnteringObject();

if (!GetIsPC(oPC)) return;

int DoOnce = GetLocalInt(OBJECT_SELF, GetTag(OBJECT_SELF));

if (DoOnce==TRUE) return;

SetLocalInt(OBJECT_SELF, GetTag(OBJECT_SELF), TRUE);

object oSlaveLord;
oSlaveLord = GetObjectByTag("Executioner");

AssignCommand(oSlaveLord, ClearAllActions());

AssignCommand(oSlaveLord, ActionAttack(GetObjectByTag("breaktable")));

    effect eEffect;
eEffect = EffectStunned();

ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eEffect, oPC, 4.0f);

int nInt;
nInt = GetObjectType(oPC);

if (nInt != OBJECT_TYPE_WAYPOINT) ApplyEffectToObject(DURATION_TYPE_TEMPORARY, EffectVisualEffect(VFX_IMP_STUN), oPC);
else ApplyEffectAtLocation(DURATION_TYPE_TEMPORARY, EffectVisualEffect(VFX_IMP_STUN), GetLocation(oPC), 4.0f);


AssignCommand(oSlaveLord, ActionAttack(oPC));

AdjustReputation(oPC, oSlaveLord, -100);

object oTarget;
object oSpawn;
location lTarget;

//Spawn #1
oTarget = GetWaypointByTag("Help_SL_Executioner");

lTarget = GetLocation(oTarget);

oSpawn = CreateObject(OBJECT_TYPE_CREATURE, "hobgoblinarchera", lTarget);

oTarget = oSpawn;

SetIsTemporaryEnemy(oPC, oTarget);

AssignCommand(oTarget, ActionAttack(oPC));

AssignCommand(oTarget, DetermineCombatRound(oPC));

//Spawn #2
oTarget = GetWaypointByTag("Help_SL_Executioner");

lTarget = GetLocation(oTarget);

oSpawn = CreateObject(OBJECT_TYPE_CREATURE, "hobgoblinarchera", lTarget);

oTarget = oSpawn;

SetIsTemporaryEnemy(oPC, oTarget);

AssignCommand(oTarget, ActionAttack(oPC));

AssignCommand(oTarget, DetermineCombatRound(oPC));

//Spawn #3
oTarget = GetWaypointByTag("Help_SL_Executioner");

lTarget = GetLocation(oTarget);

oSpawn = CreateObject(OBJECT_TYPE_CREATURE, "hobgoblinarchera", lTarget);

oTarget = oSpawn;

SetIsTemporaryEnemy(oPC, oTarget);

AssignCommand(oTarget, ActionAttack(oPC));

AssignCommand(oTarget, DetermineCombatRound(oPC));

//Spawn #4
oTarget = GetWaypointByTag("Help_SL_Executioner");

lTarget = GetLocation(oTarget);

oSpawn = CreateObject(OBJECT_TYPE_CREATURE, "hobgoblinarchera", lTarget);

oTarget = oSpawn;

SetIsTemporaryEnemy(oPC, oTarget);

AssignCommand(oTarget, ActionAttack(oPC));

AssignCommand(oTarget, DetermineCombatRound(oPC));

//Spawn #5
oTarget = GetWaypointByTag("Help_SL_Executioner");

lTarget = GetLocation(oTarget);

oSpawn = CreateObject(OBJECT_TYPE_CREATURE, "hobgoblinshaman", lTarget);

oTarget = oSpawn;

SetIsTemporaryEnemy(oPC, oTarget);

AssignCommand(oTarget, ActionAttack(oPC));

AssignCommand(oTarget, DetermineCombatRound(oPC));

}

