/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

void main()
{

object oTarget;
oTarget = OBJECT_SELF;

effect eEffect;
eEffect = EffectSleep();

ApplyEffectToObject(DURATION_TYPE_PERMANENT, eEffect, oTarget);

ExecuteScript("jr_c2_speak9", OBJECT_SELF);
}

