#include "nw_i0_tool"
/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

int StartingConditional()
{
object oPC = GetPCSpeaker();

if (!GetHasSkill(SKILL_SEARCH, oPC)) return FALSE;

if (!GetIsSkillSuccessful(oPC, SKILL_SEARCH, 10)) return FALSE;

return TRUE;
}

