/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.2

For download info, please visit:
http://www.angelfire.com/space/lilacsoul    */

int StartingConditional()
{
object oPC = GetPCSpeaker();

if (!(GetFactionGold(oPC) >= 500)) return FALSE;

return TRUE;
}

