/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

int StartingConditional()
{
object oPC = GetPCSpeaker();
int nRace = RACIAL_TYPE_HALFORC;

if (nRace == GetRacialType(oPC))
return TRUE;

else if (GetSkillRank(SKILL_LORE, oPC)>= 5) return TRUE;

return FALSE;
}

