/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.1

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

int StartingConditional()
{
object oPC = GetPCSpeaker();

int nInt;
nInt=GetLocalInt(oPC, "NW_JOURNAL_ENTRYFreeing Slaves");

if (!(nInt == 1052))// && !(GetLocalInt(GetModule(), "Derish_Slaves") == 1 ))

   return FALSE;

return TRUE;

if (GetLocalInt(GetModule(), "Derish_Slaves") != 1) return FALSE;

return TRUE;

}

