/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

//Put this on action taken in the conversation editor
void main()
{

object oPC = GetPCSpeaker();

ClearAllActions();

ActionMoveToObject(GetObjectByTag("movetocave01"));

ActionPlayAnimation(ANIMATION_LOOPING_LOOK_FAR, 1.0f, 1.0f);

object oTarget;
oTarget = GetObjectByTag("EscapedSlave");

DestroyObject(oTarget, 5.0);

}

