/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.2

For download info, please visit:
http://www.angelfire.com/space/lilacsoul    */

//Put this OnUsed
void main()
{

object oPC = GetLastUsedBy();

if (!GetIsPC(oPC)) return;

AssignCommand(oPC, ClearAllActions());

object oTarget;
oTarget = GetWaypointByTag("WP_Rope_Exit");

AssignCommand(oPC, ActionJumpToObject(oTarget));

}

