/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.2

For download info, please visit:
http://www.angelfire.com/space/lilacsoul    */

//Put this OnEnter
void main()
{

object oPC = GetEnteringObject();

if (!GetIsPC(oPC)) return;

ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(2, DAMAGE_TYPE_FIRE, DAMAGE_POWER_NORMAL), oPC);

object oTarget;
oTarget = oPC;

ApplyEffectAtLocation(DURATION_TYPE_INSTANT, EffectVisualEffect(VFX_IMP_FLAME_M), GetLocation(oTarget));

}

