/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this script OnEnter
void main()
{

object oPC = GetEnteringObject();
int nSpellCaster = GetCasterLevel(oPC);

if (!GetIsPC(oPC)) return;
/*
if ((GetLevelByClass(CLASS_TYPE_CLERIC, oPC)==0)&&
    (GetLevelByClass(CLASS_TYPE_DRUID, oPC)==0)&&
    (GetLevelByClass(CLASS_TYPE_SORCERER, oPC)==0)&&
    (GetLevelByClass(CLASS_TYPE_WIZARD, oPC)==0)&&
    (GetLevelByClass(CLASS_TYPE_ARCANE_ARCHER, oPC)==0)&&
    (GetLevelByClass(CLASS_TYPE_DIVINECHAMPION, oPC)==0)&&
    (GetLevelByClass(CLASS_TYPE_PALEMASTER, oPC)==0)&&
    (GetLevelByClass(CLASS_TYPE_DRAGONDISCIPLE, oPC)==0)&&
    (GetLevelByClass(CLASS_TYPE_SHIFTER, oPC)==0))
   return;
*/
if (nSpellCaster==0)
   return;

SendMessageToPC(oPC, "You feel a little disoriented. There is something peculiar about this area, it feels wrong to you.");

}

