#include "nw_i0_2q4luskan"
/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

//Put this OnEnter
void main()
{

object oPC = GetEnteringObject();

if (!GetIsPC(oPC)) return;

int DoOnce = GetLocalInt(OBJECT_SELF, GetTag(OBJECT_SELF));

if (DoOnce==TRUE) return;

SetLocalInt(OBJECT_SELF, GetTag(OBJECT_SELF), TRUE);

object oTarget;
object oSpawn;
location lTarget;
object oCat;
object oGuard;

oTarget = oPC;

lTarget = GetLocation(oTarget);

oSpawn = CreateObject(OBJECT_TYPE_PLACEABLE, "fallenbarrel", lTarget);

oTarget = oSpawn;

//Visual effects can't be applied to waypoints, so if it is a WP
//apply to the WP's location instead

int nInt;
nInt = GetObjectType(oTarget);

if (nInt != OBJECT_TYPE_WAYPOINT) DelayCommand(0.5, ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectVisualEffect(VFX_IMP_DESTRUCTION), oTarget));
else DelayCommand(0.5, ApplyEffectAtLocation(DURATION_TYPE_INSTANT, EffectVisualEffect(VFX_IMP_DESTRUCTION), GetLocation(oTarget)));

oTarget = GetObjectByTag("Kitty");

lTarget = GetLocation(oTarget);

DelayCommand(4.0, CreateObjectVoid(OBJECT_TYPE_CREATURE, "zep_catblackw", lTarget));

oCat = GetObjectByTag("ZEP_CATBLACKW");

AssignCommand(oCat, ClearAllActions());

AssignCommand(oCat, ActionWait(1.0f));

AssignCommand(oCat, ActionSpeakString("Meeeoooow!"));

oTarget = GetWaypointByTag("Noise01");

lTarget = GetLocation(oTarget);

oSpawn = CreateObject(OBJECT_TYPE_CREATURE, "hobgoblin002", lTarget);

oGuard = GetObjectByTag("NW_HOBGOBLIN001");

AssignCommand(oGuard, ClearAllActions());

AssignCommand(oGuard, ActionWait(10.0f));

AssignCommand(oGuard, ActionMoveToObject(GetObjectByTag("Noise")));

AssignCommand(oGuard, ActionSpeakString("HAR! Wat dat noise here?! ....HUH? INTRUDERS!!!"));

AssignCommand(oGuard, ActionAttack(oPC));

}

