/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

//Goes on creature's OnHeartbeat. Fires when not fighting or talking.
void main()
{
ActionPlayAnimation( ANIMATION_LOOPING_SIT_CROSS, 1.0, 10000.0f);
}

