/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.1

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this on action taken in the conversation editor
void main()
{

object oPC = GetPCSpeaker();

ClearAllActions();

ActionMoveToObject(GetNearestObjectByTag("SlaveExit"));

object oTarget;
oTarget = OBJECT_SELF;

DelayCommand(3.0, DestroyObject(oTarget, 0.0));

}


