/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.2

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this on action taken in the conversation editor
void main()
{

object oPC = GetPCSpeaker();

object oTarget;
oTarget = GetObjectByTag("Markessa_DOUBLE");

AssignCommand(oTarget, ClearAllActions());

AssignCommand(oTarget, ActionMoveToObject(GetObjectByTag("MarkessaDoor"), TRUE));

DestroyObject(oTarget, 5.0);

}

